### ISSUE TITLE
Importing availability zones as a sequence[str] having difficulties 

### ISSUE THREAD

**Issue by troydieter** [troydieter/cdk-api-gateway#5]
```
(.venv) PS C:\coderepo\cdk-api-gateway> cdk synth
Traceback (most recent call last):
  File "C:\coderepo\cdk-api-gateway\app.py", line 21, in <module>
    APIGWStack(app, "ApiGatewayFanOut", props=props, env=env_data)
  File "C:\python\Lib\site-packages\jsii\_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\coderepo\cdk-api-gateway\api_gw\api_gw_stack.py", line 70, in __init__
    InterfaceVpcEndpoint(self, "SNSVPCEndpoint", vpc=vpc, service=f'com.amazonaws.{self.region}.sns', subnets=SubnetSelection(availability_zones=[vpc.availability_zones]))
                                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\aws_cdk\aws_ec2\__init__.py", line 72374, in __init__
    check_type(argname="argument availability_zones", value=availability_zones, expected_type=type_hints["availability_zones"])
  File "C:\python\Lib\site-packages\typeguard\__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "C:\python\Lib\site-packages\typeguard\__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument availability_zones must be one of (Sequence[str], NoneType); got list instead

Subprocess exited with error 1
```

Need to find a way to convert the availability zone list, as retrieved from `vpc` into something that can be passed to create the interface endpoint(s)

**Comment by troydieter** [comment]
Associated with: https://github.com/troydieter/cdk-api-gateway/commit/e53e28835aaa5f18794f9df39a77eff6bef5281d

**Comment by troydieter** [comment]
Fixed by https://github.com/troydieter/cdk-api-gateway/commit/e53e28835aaa5f18794f9df39a77eff6bef5281d
